### ISSUE TITLE
 declare: -A: invalid option

### ISSUE THREAD

**Issue by jasonjckn** [rosineygp/lines#60]
`
/Users/foo/.config/zsh/bin/lines: line 4: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
/Users/foo/.config/zsh/bin/lines: line 915: syntax error near unexpected token `<'
/Users/foo/.config/zsh/bin/lines: line 915: `[<]=num_lt'
/Users/foo/.config/zsh/bin/lines: line 916: =]=num_lte: No such file or directory
/Users/foo/.config/zsh/bin/lines: line 917: [: missing `]'
/Users/foo/.config/zsh/bin/lines: line 918: [: missing `]'
/Users/foo/.config/zsh/bin/lines: line 919: [+]=num_plus: command not found
/Users/foo/.config/zsh/bin/lines: line 920: [-]=num_minus: command not found
/Users/foo/.config/zsh/bin/lines: line 921: [__STAR__]=num_multiply: command not found
/Users/foo/.config/zsh/bin/lines: line 922: [/]=num_divide: No such file or directory
/Users/foo/.config/zsh/bin/lines: line 923: [time-ms]=time_ms: command not found
/Users/foo/.config/zsh/bin/lines: line 924: [list]=_list: command not found
/Users/foo/.config/zsh/bin/lines: line 925: [list?]=list?: command not found
/Users/foo/.config/zsh/bin/lines: line 926: [vector]=_vector: command not found
/Users/foo/.config/zsh/bin/lines: line 927: [vector?]=vector?: command not found
/Users/foo/.config/zsh/bin/lines: line 928: [hash-map]=_hash_map: command not found
/Users/foo/.config/zsh/bin/lines: line 929: [map?]=hash_map?: command not found
/Users/foo/.config/zsh/bin/lines: line 930: [assoc]=assoc: command not found
/Users/foo/.config/zsh/bin/lines: line 931: [dissoc]=dissoc: command not found
/Users/foo/.config/zsh/bin/lines: line 932: [get]=get: command not found
/Users/foo/.config/zsh/bin/lines: line 933: [contains?]=contains?: command not found
/Users/foo/.config/zsh/bin/lines: line 934: [keys]=keys: command not found
/Users/foo/.config/zsh/bin/lines: line 935: [vals]=vals: command not found
/Users/foo/.config/zsh/bin/lines: line 936: [sequential?]=sequential?: command not found
/Users/foo/.config/zsh/bin/lines: line 937: [cons]=cons: command not found
/Users/foo/.config/zsh/bin/lines: line 938: [concat]=concat: command not found
/Users/foo/.config/zsh/bin/lines: line 939: [nth]=nth: command not found
/Users/foo/.config/zsh/bin/lines: line 940: [first]=_first: command not found
/Users/foo/.config/zsh/bin/lines: line 941: [rest]=_rest: command not found
/Users/foo/.config/zsh/bin/lines: line 942: [empty?]=empty?: command not found
/Users/foo/.config/zsh/bin/lines: line 943: [count]=count: command not found
/Users/foo/.config/zsh/bin/lines: line 944: [apply]=apply: command not found
/Users/foo/.config/zsh/bin/lines: line 945: [map]=map: command not found
/Users/foo/.config/zsh/bin/lines: line 946: [filter]=filter: command not found
/Users/foo/.config/zsh/bin/lines: line 947: [pmap]=pmap: command not found
/Users/foo/.config/zsh/bin/lines: line 948: [conj]=conj: command not found
/Users/foo/.config/zsh/bin/lines: line 949: [seq]=seq: command not found
/Users/foo/.config/zsh/bin/lines: line 950: [with-meta]=with_meta: command not found
/Users/foo/.config/zsh/bin/lines: line 951: [meta]=meta: command not found
/Users/foo/.config/zsh/bin/lines: line 952: [atom]=_atom: command not found
/Users/foo/.config/zsh/bin/lines: line 953: [atom?]=atom?: command not found
/Users/foo/.config/zsh/bin/lines: line 954: [deref]=deref: command not found
/Users/foo/.config/zsh/bin/lines: line 955: [reset!]=reset_BANG: command not found
/Users/foo/.config/zsh/bin/lines: line 956: [swap!]=swap_BANG: command not found
/Users/foo/.config/zsh/bin/lines: line 957: [exit!]=exit_BANG: command not found
/Users/foo/.config/zsh/bin/lines: line 958: syntax error near unexpected token `)'
/Users/foo/.config/zsh/bin/lines: line 958: `[trap!]=trap_BANG)'
`

**Comment by rosineygp** [comment]
Please send bash version it should run in bash 4+

**Comment by rosineygp** [comment]
I just test in macos using newest bash and I got following problems...

env  has a diferent behaivor and macos has no `/dev/shm` like linux.

For build need the following packages in macos

```
brew install coreutils findutils gnu-tar gnu-sed gawk gnutls gnu-indent gnu-getopt grep
```

https://apple.stackexchange.com/questions/69223/how-to-replace-mac-os-x-utilities-with-gnu-core-utilities

**Comment by rosineygp** [comment]
https://github.com/rosineygp/lines/pull/61#issuecomment-753514353

macos fix

Newest version fixed in parallel execution, but macos needs upgrade bash and coreutils (default is too old)
